name: Ćwiczenie 4

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - run: mvn exec:exec -Dexec.executable="echo" -Dexec.args="Dry run successful"
