name: Ćwiczenie 4

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
    - run: mvn exec:exec -Dexec.executable="echo" -Dexec.args="Dry run successful"
    - run: mvn test
    - run: mvn package
    - uses: actions/upload-artifact@v3
      with:
        name: ats_c4
        path: target/*.jar