name: Ćwiczenie 4

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
      - uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mvn exec:exec -Dexec.executable="echo" -Dexec.args="Dry run successful"
      - run: mvn test
      - run: mvn package
      - uses: actions/upload-artifact@v4
        with:
          name: ats_c4
          path: target/*.jar
